apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: unrestricted
  namespace: giftdeployment
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
  requiredDropCapabilities:
    - ALL
  hostIPC: false
  hostPID: false
  hostNetwork: false
  allowPrivilegeEscalation: false
  
