apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: giftdeployment
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: nyuappsec/assign3-db:v0
            env:
            - name: MYSQL_DATABASE
              value: GiftcardSiteDB
            - name: MYSQL_ROOT_PASSWORD
              value: thisisatestthing.
            - name: MYSQL_SERVICE_IP
              value: 10.106.166.130
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - mysql -h $(MYSQL_SERVICE_IP) -u root -p$(MYSQL_ROOT_PASSWORD) -e "SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.global_variables where VARIABLE_NAME in ('password_history', 'password_reuse_interval');"
          restartPolicy: OnFailure
