apiVersion: batch/v1
kind: CronJob
metadata:
  name: tablecheck
  namespace: giftdeployment
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tablecheck
            image: nyuappsec/assign3-db:v0
            env:
            - name: MYSQL_DATABASE
              value: GiftcardSiteDB
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: my-secret
                    key: MYSQLPS
            - name: MYSQL_SERVICE_IP
              value: 10.106.166.130
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - mysql -h $(MYSQL_SERVICE_IP) -u root -p$(MYSQL_ROOT_PASSWORD) -e "SELECT * FROM information_schema.SCHEMATA where SCHEMA_NAME not in ('mysql','information_schema', 'sys', 'performance_schema');"
          restartPolicy: OnFailure
