kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: giftdeployment
spec:
  selector:
    app: mysql-container
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
