apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl  
  namespace: giftdeployment  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: giftdeployment  
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "delete"]      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
  namespace: giftdeployment  
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
