apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-test
  namespace: giftdeployment
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-test
            image: nyuappsec/assign3-db:v0
            env:
            - name: MYSQL_DATABASE
              value: GiftcardSiteDB
            - name: MYSQL_ROOT_PASSWORD
              value: thisisatestthing.
            imagePullPolicy: IfNotPresent
            command:
            - "/bin/sh"
            - "-c"
            - "mysql --version"
            
          restartPolicy: OnFailure
